### PR TITLE
Clean up code

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Review by maudetes — CHANGES_REQUESTED** [review]
Maybe adding `this->` everywhere is a bit heavy. Especially since the notation uses an underscore prefix to highlight that it is a private attribute.
In any case, if we want to keep `this->` make sure it is consistent between files. It has been added on the grpc side but not on the rest side (rest_server.cpp).

**Comment by GuillaumeGomez** [comment]
I only made the change when it seemed useful to me. So if you prefer that I remove this change, I'm fine with it. :)

**Comment by maudetes** [comment]
In this case, I would prefer to remove it.

**Comment by GuillaumeGomez** [comment]
Perfect, removing then!

**Review by maudetes — APPROVED** [review]
Looks good to me !

**Pull request merged**
